#454: Catalog for dashboard
geosolutions-it/MapStore2-C040 pull request #483
Opened 2021-09-27 13:23 UTC by dsuren1

## Description
This PR updates Mapstore submodule with stable version (`2021.02.xx`) enabling catalog for dashboards with necessary configs 

## Issues
 - #454 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

**What is the current behavior?** (You can also link to an open issue here)
Catalog is not available in dashboard

**What is the new behavior?**
Catalog is now available in dashboard editor allowing user to configure catalog services

**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

2021-11-02 14:09 UTC, offtherailz requested changes
Uff... sorry my fault. Master changed a lot so migration guidelines are not so aligned yet. 
Can you verify if the real war file works? I'm afraid it doesn't because of `publicPath` setting. 
Please referer to this:
- https://mapstore.readthedocs.io/en/2021.02.xx/developer-guide/mapstore-migration-guide/
There are some minor things like `publicPath`, changes in pom files and servlet to set.

2021-11-03 06:22 UTC, dsuren1 commented on configs/localConfig.json
> +    "method": "bearer"
Mmmm... definitely not intentional. Probably a result of resolving conflicts, I believe

2021-11-03 09:10 UTC, offtherailz commented on configs/localConfig.json
> +    "method": "bearer"
good, please restore it to avoid unneeded changes in the history

2021-11-03 09:18 UTC, dsuren1 commented
Hi @offtherailz 
Updated as per migration guidelines. Kindly let me know for any changes. Thanks!

2021-11-09 17:29 UTC, offtherailz approved these changes

2021-11-09 17:29 UTC, merged

2021-11-09 17:30 UTC, offtherailz commented
LGTM. I didn't  tested it locally. Going to test in test environment