#538 update project to 2022.01.xx
geosolutions-it/MapStore2-C040 pull request #543
Opened 2022-03-21 16:11 UTC by MV88

## Description

This PR updates the project to latest 2022.01.xx

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: project update

## Issue

**What is the current behavior?**

#538 

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

this is in draft because of #541

2022-03-21 17:23 UTC, offtherailz commented
For the migration guide you are right. They has been changed here but never updated with the fixed versions.

https://github.com/geosolutions-it/MapStore2/commit/1760520f5956823c9b5da23994ffcae66c4ae346

We should document it better. Please open a PR or an issue about the points to fix/improve in migration guidelines.

2022-03-22 09:12 UTC, MV88 commented
@offtherailz there you go

https://github.com/geosolutions-it/MapStore2/issues/7997

2022-03-22 14:46 UTC, offtherailz requested changes
Just update `proxy.properties` aligning to latest master, when 3DTiles PR is ported

2022-03-22 14:46 UTC, offtherailz commented on web/src/main/resources/proxy.properties
> +reqtypeWhitelist.generic = (.*exist.*)|(.*pdf.*)|(.*map.*)|(.*wms.*)|(.*wmts.*)|(.*tms.*)|(.*wfs.*)|(.*ows.*)|(.*spatialreference.*)|(.*wps.*)
You will have to update also this with new types for 3D tiles. See proxy.properties  updated in MapStore when you merge PR from Stefano

2022-03-23 09:11 UTC, offtherailz approved these changes

2022-03-23 17:17 UTC, merged